version: '3.1'  # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  helloService:
    image: internaldocking

  goingOutService:
    image: externaldocking
    ports:
        - 8181:8080
    depends_on: 
        - helloService